name: HH-Recruiter-FE Workflow

on:
  push:
    branches:
      - create-workflow #Temporary
  pull_request:
    branches:
      - develop
    types:
      - closed
  create:
    tags:
      - '*'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #      - name: Configure AWS Credentials
      #        uses: aws-actions/configure-aws-credentials@v1
      #        with:
      #          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #          aws-region: ap-southeast-1

      #      - name: Download Dev Env File
      #        if: github.ref == 'refs/heads/create-workflow'
      #        run: aws s3 cp s3://workflow-github-action/env-file/hh-be-core/develop/.env.staging .env.staging

      - name: Build Next.js
        run: npm install

      - name: Build
        run: npm run build:live

      - name: Delete Previous Next.js on Develop
        if: github.ref == 'refs/heads/create-workflow' #Temporary
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
          script: |
            sudo rm -rf /home/ubuntu/admin/recruiter/tmp
            sudo mkdir /home/ubuntu/admin/recruiter/tmp
            sudo chmod 777 /home/ubuntu/admin/recruiter/tmp

      - name: Delete Previous Next.js on Production
        if: github.ref == 'refs/heads/create-workflow' #Temporary
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }} #Temporary
          username: ${{ secrets.EC2_USERNAME_DEV }} #Temporary
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }} #Temporary
          script: |
            sudo rm -rf /home/ubuntu/admin/recruiter/tmp
            sudo mkdir /home/ubuntu/admin/recruiter/tmp
            sudo chmod 777 /home/ubuntu/admin/recruiter/tmp

      - name: Copy SSH Develop Key to File
        if: github.ref == 'refs/heads/create-workflow' ##Temporary
        run: |
          echo "$EC2_PRIVATE_KEY_DEV" > EC2_KEY.pem
          chmod 600 EC2_KEY.pem
        env:
          EC2_PRIVATE_KEY_DEV: ${{ secrets.EC2_PRIVATE_KEY_DEV }}

      - name: Copy SSH Production Key to File
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        run: |
          echo "$EC2_PRIVATE_KEY_DEV" > EC2_KEY.pem
          chmod 600 EC2_KEY.pem
        #^^^^^^Temporary^^^^  
        env:
          EC2_PRIVATE_KEY_DEV: ${{ secrets.EC2_PRIVATE_KEY_DEV }} #Temporary

      - name: Update known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST_DEV }} >> ~/.ssh/known_hosts

      - name: Copy build files to Develop EC2 instance
        if: github.ref == 'refs/heads/create-workflow' #Temporary
        run: |
          scp -i EC2_KEY.pem -r dist ${{ secrets.EC2_USERNAME_DEV }}@${{ secrets.EC2_HOST_DEV }}:/home/ubuntu/admin/recruiter/tmp/dist
          scp -i EC2_KEY.pem package.json ${{ secrets.EC2_USERNAME_DEV }}@${{ secrets.EC2_HOST_DEV }}:/home/ubuntu/admin/recruiter/tmp/package.json

      - name: Copy build files to Production EC2 instance
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        run: |
          scp -i EC2_KEY.pem -r dist ${{ secrets.EC2_USERNAME_DEV }}@${{ secrets.EC2_HOST_DEV }}:/home/ubuntu/admin/recruiter/tmp/dist
          scp -i EC2_KEY.pem package.json ${{ secrets.EC2_USERNAME_DEV }}@${{ secrets.EC2_HOST_DEV }}:/home/ubuntu/admin/recruiter/tmp/package.json
      #^^^^^^^^^^^^^^^^^Temporary^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  DeployOnDev:
    needs: Build
    if: github.ref == 'refs/heads/create-workflow'
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies and Run Next.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
          script: |
            export PATH=/usr/local/nodejs/bin:$PATH
            cd /home/ubuntu/admin/recruiter/tmp
            npm install
            pm2 delete admin-recruiter
            pm2 start npm --name "admin-recruiter" -- dev:live

  DeployOnTagCreation:
    needs: Build
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies and Run Next.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }} #Temporary
          username: ${{ secrets.EC2_USERNAME_DEV }} #Temporary
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }} #Temporary
          script: |
            export PATH=/usr/local/nodejs/bin:$PATH
            cd /home/ubuntu/admin/recruiter/tmp
            npm install
            pm2 delete admin-recruiter
            pm2 start npm --name "admin-recruiter" -- run serve